VERSION = 1.2.0

obj-so += math

INC_FLAGS += -I $(inc_dir)
EXTRA_LIBD += -L $(lib_dir)
EXTRA_LIBS +=
EXTRA_LIBS +=

target = lib$(obj-so).$(VERSION).so

TARGET_IS_LIB = 1

include $(TOPDIR)/files.mk
include $(TOPDIR)/rules.mk
